import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans, Poppins } from 'next/font/google'

const poppins = Poppins({ variable:'--font-poppins' , weight: ["700"], subsets:["latin"] })
const openSans = Open_Sans({ variable:'--font-open-sans' , weight: ["400", "600", "700"], subsets:["latin"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${openSans.variable} font-sans`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
